### ISSUE TITLE
Studies Management Page to view, filter, and export studies in the curation app

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-ui#91]
**Description:**
As a curator
I need a studies management page separate from the Publication Management page
That allows me to identify studies with a particular EFO or reported trait

**Management Rules:**
Rule 1: A menu item should be added on the top bar of the curation app with label "Studies"
Rule 2: When the "Studies" Label is clicked on the menu, it should route to a url /studies
Rule 3: The view of the /studies page should contain a Paginated Tabular View of all studies in the database
Rule 4: Columns of the Tabular View should include: GCST, PMID, Publication Date, Author Name, Title, EFO Trait, Reported Trait, Notes
Rule 5: The note could be a snippet, expandable box *
Rule 6: The table should have an Export button for exporting the results of the search
Rule 7: There should be Filter Button below the table similar to submission management page or somewhere else
Rule 8: Filter should include: EFO Trait, Reported Trait, Study Flag, and Note
Rule 9: EFO Trait Filter ui component should be a Typeahead Autosuggest search Box
Rule 10: Reported Trait Filter ui component should be a Typeahead Autosuggest search Box
Rule 11: Note Filter ui component should be a Typeahead Autosuggest search Box
Rule 12: Filter by study flag should be a drop down combo box.

**Comment by ljwh2** [comment]
@earlEBI to test this with combinations of search terms, thanks

**Comment by earlEBI** [comment]
The table looks good but the search functionality needs some tweaks: 
1. The reported trait box needs to be wider because at the moment some long traits are indecipherable: 
<img width="1327" alt="Screenshot 2022-10-12 at 13 23 17" src="https://user-images.githubusercontent.com/61545198/195372027-79a46a79-c3df-4a38-bf2b-b909de6bbba7.png">

2. It looks as if the list is capped at a certain number (here, halfway through the alphabet), which means you can't select, for example "stroke". 
<img width="1178" alt="Screenshot 2022-10-12 at 13 23 52" src="https://user-images.githubusercontent.com/61545198/195372379-8fb10ffe-3dfe-4629-a02f-7d7b1fe07347.png">


3. If I search for partial epilepsy in the EFO field, the returned studies have NA listed in the EFO trait column:
<img width="1575" alt="Screenshot 2022-10-12 at 16 01 41" src="https://user-images.githubusercontent.com/61545198/195378681-15b989cd-5923-414f-b334-5f7e524f132d.png">


4. The Export Data button seems to do nothing. It's important this works especially as search results are capped to showing max 20 results per page. 

5. I use the corresponding page in the old Curation App to filter by curator and curation status - are these needed on this new depocuration page or will that functionality be somewhere else?

**Comment by ala-ebi** [comment]
1. fixed
2. fixed
3. fixed
4. pending
5. feature will be added in the future when we create APIs to assign curators

**Comment by earlEBI** [comment]
1-3 now look good!

6. I've also noticed if you search for eg. Alzheimer's disease, it returns all studies with reported trait *containing* Alzheimer's disease. I'm not sure if this is what we want? I *think* would be better to return only exact results. 

7. Also, searching for Alzheimer's disease, if I try to page through the results, the search resets to all 147780 results. So I can't see more than 20. Don't know if this is related to work on point 4.

**Comment by ala-ebi** [comment]
good point @earlEBI 
7. fixed

**Comment by sajo-ebi** [comment]
@earlEBI for point we can make changes to make the exact search come on top of search results , will that be fine ?

**Comment by earlEBI** [comment]
@sajo-ebi I think I'd be happy with that. but yes we'll see what other curators want.

**Comment by earlEBI** [comment]
@ala-ebi 7. is good now, thanks!

**Comment by sajo-ebi** [comment]
@earlEBI for point  the exact match will be returned on top of the results

**Comment by earlEBI** [comment]
Curators discussed and think exact match returned on top is fine, thanks. 

Point 8: Again for reported trait, we wondered if it would be possible to search for partial words such as "alz" or words that aren't traits on their own, such as "MTAG"? At the moment, it seems you have to select a whole trait from the dropdown to return relevant results. 
Similar partial match functionality seems to exist for the Catalog UI.

**Comment by sajo-ebi** [comment]
@earlEBI the patch has been deployed, the partial search should work for Reported Traits, EFO Traits & notes field, kindly validate

**Comment by earlEBI** [comment]
@sajo-ebi looks good!
